"""Initial usage-owned schema. Frozen migration; do not import live ORM models."""

import sqlalchemy as sa
from alembic import op

revision = "0003_usage"
down_revision = "0002_tasks"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS usage")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=150), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
        schema="usage",
    )
    op.create_index(
        op.f("ix_usage_observations_user_id"),
        "observations",
        ["user_id"],
        unique=False,
        schema="usage",
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("observations", schema="usage")
    op.execute("DROP SCHEMA usage")
