[alembic]
script_location = %(here)s/migrations
prepend_sys_path = %(here)s/src
path_separator = os
version_locations = %(here)s/migrations/versions:%(here)s/src/komorebi_server/capabilities/tasks/migrations:%(here)s/src/komorebi_server/capabilities/usage/migrations:%(here)s/src/komorebi_server/capabilities/conversations/migrations:%(here)s/src/komorebi_server/capabilities/learn/migrations
