"""Initial conversations-owned schema. Frozen migration; do not import live ORM models."""

import sqlalchemy as sa
from alembic import op

revision = "0004_conversations"
down_revision = "0003_usage"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS conversations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
        sa.UniqueConstraint("thread_id", "sequence"),
        schema="conversations",
    )
    op.create_index(
        op.f("ix_conversations_messages_thread_id"),
        "messages",
        ["thread_id"],
        unique=False,
        schema="conversations",
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="conversations",
    )
    op.create_index(
        op.f("ix_conversations_threads_user_id"),
        "threads",
        ["user_id"],
        unique=False,
        schema="conversations",
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("threads", schema="conversations")
    op.drop_table("messages", schema="conversations")
    op.execute("DROP SCHEMA conversations")
