import { completed, daysFromNow, failedOperation, minutesAgo, newId, nowIso, snapshot, wait } from '../../../shared/api/mock'
import type { Operation, Snapshot } from '../../../shared/contracts/common'
import type { SeriesEditScope, Task, TaskChange, TaskDraft, TaskFilter, TaskSeries } from './types'

/*
 * Tasks HTTP adapter (mock). Real endpoints: /api/v1/tasks/...
 * Mutations carry an Idempotency-Key; repeating a completion records one event.
 */
const series: TaskSeries[] = [
  { id: 'ser_water', title: 'Water the balcony plants', rule: 'every 3 days', lookaheadDays: 14 },
  { id: 'ser_review', title: 'Weekly review', rule: 'every Sunday 18:00', lookaheadDays: 28 },
]

let tasks: Task[] = [
  { id: 'tsk_1', title: 'Outline chapter 4 recall prompts', description: 'Draft 8 prompts from the Feynman lecture notes. Approve the good ones before Thursday.', status: 'open', dueAt: daysFromNow(0, 18), estimateMinutes: 45, effort: 'deep', context: 'study', priority: true, revision: 3, createdAt: minutesAgo(3000) },
  { id: 'tsk_2', title: 'Book dentist appointment', status: 'open', dueAt: daysFromNow(2, 12), estimateMinutes: 10, effort: 'light', context: 'admin', priority: false, revision: 1, createdAt: minutesAgo(1800) },
  { id: 'tsk_3', title: 'Reply to landlord about radiator', status: 'in_progress', dueAt: daysFromNow(-1, 17), estimateMinutes: 15, effort: 'light', context: 'admin', priority: false, revision: 2, createdAt: minutesAgo(4200) },
  { id: 'tsk_4', title: 'Water the balcony plants', status: 'open', dueAt: daysFromNow(1, 8), estimateMinutes: 10, effort: 'light', context: 'home', priority: false, seriesId: 'ser_water', occurrenceKey: '2026-09-06', revision: 1, createdAt: minutesAgo(600), originRef: { owner: 'household', kind: 'maintenance_template', id: 'mt_plants' } },
  { id: 'tsk_5', title: 'Weekly review', status: 'open', dueAt: daysFromNow(1, 18), estimateMinutes: 40, effort: 'medium', context: 'reflection', priority: false, seriesId: 'ser_review', occurrenceKey: '2026-09-06', revision: 1, createdAt: minutesAgo(9000) },
  { id: 'tsk_6', title: 'Practise self-introduction (Japanese)', status: 'open', dueAt: daysFromNow(3, 19), estimateMinutes: 20, effort: 'medium', context: 'study', priority: false, revision: 1, createdAt: minutesAgo(700), originRef: { owner: 'japanese', kind: 'skill_target', id: 'skill_intro' } },
  { id: 'tsk_7', title: 'Replace kitchen tap filter', status: 'completed', dueAt: daysFromNow(-3, 10), estimateMinutes: 20, effort: 'light', context: 'home', priority: false, revision: 4, createdAt: minutesAgo(20000), completedAt: minutesAgo(3600), originRef: { owner: 'household', kind: 'maintenance_template', id: 'mt_filter' } },
  { id: 'tsk_8', title: 'Send accountant the Q3 receipts', status: 'completed', estimateMinutes: 25, effort: 'medium', context: 'admin', priority: false, revision: 2, createdAt: minutesAgo(30000), completedAt: minutesAgo(1400) },
  { id: 'tsk_9', title: 'Read: Attention and working memory (pp. 41–58)', status: 'open', estimateMinutes: 35, effort: 'deep', context: 'study', priority: false, revision: 1, createdAt: minutesAgo(500) },
  { id: 'tsk_10', title: 'Order new running shoes', status: 'canceled', estimateMinutes: 15, effort: 'light', context: 'errands', priority: false, revision: 2, createdAt: minutesAgo(40000) },
]

let changes: TaskChange[] = [
  { id: 'chg_1', taskId: 'tsk_1', at: minutesAgo(3000), kind: 'created', detail: 'Converted from capture cap_2' },
  { id: 'chg_2', taskId: 'tsk_1', at: minutesAgo(2000), kind: 'prioritized', detail: 'Marked as priority' },
  { id: 'chg_3', taskId: 'tsk_1', at: minutesAgo(400), kind: 'updated', detail: 'Estimate changed 30 → 45 min' },
  { id: 'chg_4', taskId: 'tsk_7', at: minutesAgo(3600), kind: 'completed', detail: 'Completed · next occurrence generated by Household' },
]

const completionKeys = new Set<string>()

function matches(task: Task, filter: TaskFilter): boolean {
  if (filter.status !== 'all' && task.status !== filter.status) return false
  if (filter.context && task.context !== filter.context) return false
  if (filter.due && filter.due !== 'any') {
    if (!task.dueAt) return false
    const due = new Date(task.dueAt)
    const now = new Date()
    const endOfDay = new Date(now)
    endOfDay.setHours(23, 59, 59, 999)
    if (filter.due === 'today' && !(due <= endOfDay && due >= new Date(now.setHours(0, 0, 0, 0)))) return false
    if (filter.due === 'overdue' && due >= new Date()) return false
    if (filter.due === 'week' && due.getTime() - Date.now() > 7 * 86_400_000) return false
  }
  return true
}

export async function listTasks(filter: TaskFilter): Promise<Snapshot<Task[]>> {
  await wait()
  const ordered = [...tasks]
    .filter((task) => matches(task, filter))
    .sort((a, b) => Number(b.priority) - Number(a.priority) || (a.dueAt ?? '9').localeCompare(b.dueAt ?? '9'))
  return snapshot(ordered)
}

export async function listContexts(): Promise<string[]> {
  await wait(80)
  return Array.from(new Set(tasks.map((task) => task.context).filter((value): value is string => Boolean(value)))).sort()
}

export async function getTask(id: string): Promise<Snapshot<{ task: Task; series?: TaskSeries; history: TaskChange[] }> | null> {
  await wait(160)
  const task = tasks.find((item) => item.id === id)
  if (!task) return null
  const taskSeries = task.seriesId ? series.find((item) => item.id === task.seriesId) : undefined
  return snapshot({ task, series: taskSeries, history: changes.filter((change) => change.taskId === id).sort((a, b) => b.at.localeCompare(a.at)) })
}

export async function createTask(draft: TaskDraft, idempotencyKey: string): Promise<Operation<Task>> {
  await wait(300)
  const existing = tasks.find((task) => task.id === idempotencyKey)
  if (existing) return completed(existing)
  if (!draft.title.trim()) return failedOperation('validation', false, 'A task needs a title.')
  const task: Task = {
    id: newId('tsk'),
    title: draft.title.trim(),
    description: draft.description,
    status: 'open',
    dueAt: draft.dueAt,
    estimateMinutes: draft.estimateMinutes,
    effort: draft.effort,
    context: draft.context,
    priority: draft.priority ?? false,
    revision: 1,
    createdAt: nowIso(),
  }
  if (draft.recurrence) {
    const created: TaskSeries = { id: newId('ser'), title: task.title, rule: draft.recurrence, lookaheadDays: 14 }
    series.push(created)
    task.seriesId = created.id
    task.occurrenceKey = new Date().toISOString().slice(0, 10)
  }
  tasks = [task, ...tasks]
  changes = [{ id: newId('chg'), taskId: task.id, at: nowIso(), kind: 'created', detail: 'Created' }, ...changes]
  return completed(task)
}

export async function updateTask(id: string, patch: Partial<TaskDraft>, expectedRevision: number, scope: SeriesEditScope = 'occurrence'): Promise<Operation<Task>> {
  await wait(240)
  const task = tasks.find((item) => item.id === id)
  if (!task) return failedOperation('not_found', false, 'Task no longer exists.')
  if (task.revision !== expectedRevision) return failedOperation('revision_conflict', false, 'Someone edited this task since you opened it. Reload to see the newer version.')
  const next: Task = { ...task, ...patch, revision: task.revision + 1 }
  tasks = tasks.map((item) => (item.id === id ? next : item))
  if (scope === 'series' && task.seriesId) {
    const idx = series.findIndex((item) => item.id === task.seriesId)
    if (idx >= 0 && patch.title) series[idx] = { ...series[idx], title: patch.title }
  }
  changes = [{ id: newId('chg'), taskId: id, at: nowIso(), kind: patch.priority !== undefined ? 'prioritized' : 'updated', detail: scope === 'series' ? 'Updated the whole series' : 'Updated this occurrence' }, ...changes]
  return completed(next)
}

export async function completeOccurrence(id: string, idempotencyKey: string): Promise<Operation<Task>> {
  await wait(260)
  const task = tasks.find((item) => item.id === id)
  if (!task) return failedOperation('not_found', false)
  if (completionKeys.has(idempotencyKey) || task.status === 'completed') return completed(task)
  completionKeys.add(idempotencyKey)
  const next: Task = { ...task, status: 'completed', completedAt: nowIso(), revision: task.revision + 1 }
  tasks = tasks.map((item) => (item.id === id ? next : item))
  changes = [{ id: newId('chg'), taskId: id, at: nowIso(), kind: 'completed', detail: 'Completed · occurrence fact published' }, ...changes]
  return completed(next)
}

export async function reopenOccurrence(id: string): Promise<Operation<Task>> {
  await wait(200)
  const task = tasks.find((item) => item.id === id)
  if (!task) return failedOperation('not_found', false)
  const next: Task = { ...task, status: 'open', completedAt: undefined, revision: task.revision + 1 }
  tasks = tasks.map((item) => (item.id === id ? next : item))
  changes = [{ id: newId('chg'), taskId: id, at: nowIso(), kind: 'reopened', detail: 'Reopened' }, ...changes]
  return completed(next)
}

export async function cancelOccurrence(id: string, scope: SeriesEditScope): Promise<Operation<Task>> {
  await wait(200)
  const task = tasks.find((item) => item.id === id)
  if (!task) return failedOperation('not_found', false)
  const next: Task = { ...task, status: 'canceled', revision: task.revision + 1 }
  tasks = tasks.map((item) => (item.id === id ? next : item))
  changes = [{ id: newId('chg'), taskId: id, at: nowIso(), kind: 'canceled', detail: scope === 'series' ? 'Series paused; later occurrences will not generate' : 'This occurrence canceled; later occurrences intact' }, ...changes]
  return completed(next)
}

/** Bounded candidate list consumed by Capacity and Today (public query, no private fields). */
export async function listActionCandidates(limit = 8): Promise<Snapshot<Task[]>> {
  await wait(150)
  return snapshot(tasks.filter((task) => task.status === 'open' || task.status === 'in_progress').slice(0, limit))
}
