"""Initial platform-owned schema. Frozen migration; do not import live ORM models."""

import sqlalchemy as sa
from alembic import op

revision = "0001_platform"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS platform")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_budgets",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.CheckConstraint("used >= 0 AND reserved >= 0"),
        sa.PrimaryKeyConstraint("user_id", "month"),
        schema="platform",
    )
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reserved_units", sa.Integer(), nullable=False),
        sa.Column("used_units", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_ai_runs_user_id"), "ai_runs", ["user_id"], unique=False, schema="platform"
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_audit_actor_id"), "audit", ["actor_id"], unique=False, schema="platform"
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_files_user_id"), "files", ["user_id"], unique=False, schema="platform"
    )
    op.create_table(
        "heartbeats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_table(
        "idempotency",
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=200), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("actor_id", "operation", "key"),
        schema="platform",
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dedupe_key", sa.String(length=250), nullable=False),
        sa.Column("module", sa.String(length=60), nullable=False),
        sa.Column("type", sa.String(length=150), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("external", sa.Boolean(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempts >= 0 AND max_attempts > 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
        schema="platform",
    )
    op.create_index(
        "ix_jobs_claim",
        "jobs",
        ["status", "available_at", "lease_until"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "login_tickets",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("digest"),
        schema="platform",
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=60), nullable=False),
        sa.Column("type", sa.String(length=150), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_outbox_actor_id"), "outbox", ["actor_id"], unique=False, schema="platform"
    )
    op.create_index(
        op.f("ix_platform_outbox_dispatched_at"),
        "outbox",
        ["dispatched_at"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "preferences",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        schema="platform",
    )
    op.create_table(
        "receipts",
        sa.Column("consumer", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("consumer", "event_id"),
        schema="platform",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("csrf", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_sessions_user_id"),
        "sessions",
        ["user_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("users", schema="platform")
    op.drop_table("sessions", schema="platform")
    op.drop_table("receipts", schema="platform")
    op.drop_table("preferences", schema="platform")
    op.drop_table("outbox", schema="platform")
    op.drop_table("notifications", schema="platform")
    op.drop_table("login_tickets", schema="platform")
    op.drop_table("jobs", schema="platform")
    op.drop_table("idempotency", schema="platform")
    op.drop_table("heartbeats", schema="platform")
    op.drop_table("files", schema="platform")
    op.drop_table("credentials", schema="platform")
    op.drop_table("audit", schema="platform")
    op.drop_table("ai_runs", schema="platform")
    op.drop_table("ai_budgets", schema="platform")
    op.execute("DROP SCHEMA platform")
