/*
 * Registered application routes. Contributions and command-palette entries link
 * only to these, matching the spec's "validated registered application route" rule.
 */
export const routes = {
  today: '/today',
  capture: '/capture',
  goals: '/goals',
  tasks: '/tasks',
  calendar: '/calendar',
  calendarConnections: '/calendar/connections',
  plan: '/plan',
  learn: '/learn',
  artifacts: '/learn/artifacts',
  practice: '/learn/practice',
  library: '/learn/library',
  librarySearch: '/learn/library/search',
  notes: '/learn/notes',
  sessions: '/learn/sessions',
  resume: '/learn/resume',
  review: '/learn/review',
  exams: '/learn/exams',
  japanese: '/learn/japanese',
  connections: '/learn/connections',
  home: '/home',
  homeConnections: '/home/connections',
  scenes: '/home/scenes',
  alerts: '/home/alerts',
  training: '/life/training',
  habits: '/life/habits',
  reflection: '/life/review',
  people: '/life/people',
  household: '/life/household',
  shopping: '/life/household/shopping',
  maintenance: '/life/household/maintenance',
  finance: '/life/finance',
  briefing: '/briefing',
  briefingSources: '/briefing/sources',
  assistant: '/assistant',
  voice: '/voice',
  automations: '/automations',
  usage: '/history/usage',
  conversations: '/conversations',
  memory: '/memory',
  improvements: '/improvements',
  settings: '/settings',
} as const

export type RouteKey = keyof typeof routes
