"""Initial tasks-owned schema. Frozen migration; do not import live ORM models."""

import sqlalchemy as sa
from alembic import op

revision = "0002_tasks"
down_revision = "0001_platform"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS tasks")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "changes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="tasks",
    )
    op.create_index(
        op.f("ix_tasks_changes_task_id"), "changes", ["task_id"], unique=False, schema="tasks"
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimate_minutes", sa.Integer(), nullable=True),
        sa.Column("effort", sa.String(length=10), nullable=True),
        sa.Column("context", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('open', 'in_progress', 'completed', 'canceled')"),
        sa.CheckConstraint("estimate_minutes IS NULL OR estimate_minutes > 0"),
        sa.CheckConstraint("revision > 0"),
        sa.PrimaryKeyConstraint("id"),
        schema="tasks",
    )
    op.create_index(
        "ix_tasks_owner_status", "tasks", ["user_id", "status", "id"], unique=False, schema="tasks"
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("tasks", schema="tasks")
    op.drop_table("changes", schema="tasks")
    op.execute("DROP SCHEMA tasks")
